name: Release App
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-laters, ubuntu-l20.0.4, windows-latest]
    runs-on: ${{ matrix.platgorm }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies ( ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        # You can remove
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev librsvg2-dev

      - name: Rust setup
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "yarn"

      - name: Install Frontend Dep
        run: yarn

      - name: Build Frontend
        run: yarn build

      - name: Build backend
        uses: tauri-apps/tauri-action@v0

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagname: ${{ github.ref_name }}
          releaseName: "App Name v__VERSION__"
          releaseBody: "See the assets to download and indtall the version."
          releaseDraft: true
          prerelease: false
